---
galaxy_info:
  author: Steve Fulmer
  description: Role driverless_ai_deploy for stevefulme1.h2o_ai
  license: GPL-3.0-or-later
  min_ansible_version: '2.16'
  galaxy_tags:
    - h2o_ai
dependencies: []
