---
- name: Validate required variables
  ansible.builtin.assert:
    that: wave_deploy_api_url is defined
    quiet: true

- name: Execute wave_deploy
  ansible.builtin.debug:
    msg: "Role wave_deploy for stevefulme1.h2o_ai"
